### ISSUE TITLE
How to convert the MovieLens dataset into ml-tag format?

### ISSUE THREAD

**Issue by rezacsedu** [hexiangnan/attentional_factorization_machine#1]
Hi,

How to get the MovieLens dataset into ml-tag format?
I understand that the structure of the data folder has to be:

ml-tag
    ml-tag.train.libfm
    ml-tag.validation.libfm
    ml-tag.test.libfm

**Comment by gaoshuming** [comment]
I faced to the same issues and the url can't opened.
How to get the dataset.

**Comment by hexiangnan** [comment]
Hi,
sorry for the trouble! I have uploaded the required datasets. Please take a look.

**Comment by rezacsedu** [comment]
@hexiangnan thanks so much.
