### ISSUE TITLE
About the training script

### ISSUE THREAD

**Issue by qmick** [hexiangnan/attentional_factorization_machine#4]
Thanks for your sharing.
I found two issues while trying to run the training script (at Performance Comparison->Train): 
```bash
python FM.py --dataset ml-tag --epoch 20 --pretrain -1 --batch_size 4096 --lr 0.01 --keep 0.7
```
It seems an additional argument `--hidden_factor 16` is required to match the description `we set the dimension of the embedding factor to be 16`.

And 
```bash
python AFM.py --dataset ml-tag --epoch 20 --pretrain 1 --batch_size 4096 --hidden_factor [16,16] --keep [1.0,0.5] --lamda_attention 100.0 --lr 0.1
```
This script do not save the model to file and will cause `OSError: File ../pretrain/afm_ml-tag_16/ml-tag_16.meta does not exist.` while evaluating. I change `--pretrain 1` to `--pretrain 2` then it works fine.

Are these modifications correct? Or I am misreading something?

**Comment by hexiangnan** [comment]
#1: Yes, --hidden_factor 16 is required for FM.
#2: You're right. There is a mistake at line 367 of AFM.py, which generate a wrong path for pretrained model with the prefix 'afm_'. I have updated the code and sorry for the trouble!
